version: '3.5'
services:
  eventstore:
    container_name: talk-eventstore
    image: eventstore/eventstore:latest
    ports:
    - 2113:2113
    - 1113:1113
    environment:
    - EVENTSTORE_EXT_HTTP_PORT=2113
    - EVENTSTORE_EXT_TCP_PORT=1113
